### PR TITLE
Added support for custom manual pages in the esdoc.json file

### PR DESCRIPTION
**Pull request by heath-guidewire**
- The format for these is `"manual": {"customPages": [{"label": "custom label", "paths": ["customPath.md"]}, ...]}`
- Validates if a custom page definition is bad and outputs warning as to why, indicating it is being skipped
- Includes updates to the tests

### CODE REVIEW

**Comment by heath-guidewire** [comment]
Even master has one build failure: 
```
 1) ComputedMethod: has computed method:

      AssertionError: selector: "[data-ice="target"]:nth-of-type(3)",
actual:  public [`${foo}`]() this is [${foo}] 
expect: public [`${ foo }`]()
      + expected - actual

      -false
      +true
      
      at Function._assert3.default.includes (test/src/util.js:51:3)
      at Context.<anonymous> (test/src/BuilderTest/ComputedMethodTest.js:10:12)

```

**Comment by typhonrt** [comment]
Yeah.. As mentioned I'm not accepting any PRs into this repo as it will be deleted shortly. This repo is not published on NPM, so even if things were merged it's no different than you working on your own fork of ESDoc `0.5.2`. If you need the changes you made I recommend you just make your own fork of ESDoc or this repo and use that by linking from Github in `package.json` like:
"esdoc": "git+https://git@github.com/heath-guidewire/esdoc.git"

Again apologies for closing this PR as it doesn't make sense to merge anything at this time. 

BTW if there are build errors with any current tests in this repo it's likely due to the open versioning of Babel and any subtle changes with any breaking changes there since this repo hasn't been tested for months; there was one such in the last 6 months, etc.

**Comment by heath-guidewire** [comment]
I do have my own fork.  Which I will use internally… FYI, deleting your fork might cause a serious disruption for a lot of users of it out there.  Consider emptying the fork out, but leave the README pointing to your new project

**Comment by typhonrt** [comment]
@heath-guidewire deleting this repo will not delete your personal fork. It's not very likely that many are depending on this particular repo again since it's not published on NPM. If someone happens to be directly linking to it then they really should update to the mainline ESDoc version. I will once TJSDoc is published on NPM clear out this repo and post a note about it being deleted in 2 weeks after that point.

**Pull request closed without merging**
