### PR TITLE
Add custom manual pages

### PR DESCRIPTION
**Pull request by heath-guidewire**
- The format for these is `"manual": {"customPages": [{"label": "custom label", "paths": ["customPath.md"]}, ...]}`
- Validates if a custom page definition is bad and outputs warning as to why, indicating it is being skipped
- Includes updates to the tests

### CODE REVIEW

**Comment by heath-guidewire** [comment]
I wish I had forked your repo rather than the original... I'd love to get this change into your fork because we are using it within our company.

**Comment by typhonrt** [comment]
@heath-guidewire this PR is definitely messed up due to trying to combine sources from a different fork of ESDoc, so it certainly can't be merged. 

I should also note that I am releasing later this week the spiritual successor to ESDoc called TJSDoc. I've hard forked ESDoc at `0.5.2` and have spent the last 2+ months improving everything considerably. There are lot's of new features. Please see the [TJSDoc organization](https://github.com/typhonjs-node-tjsdoc). The manual support in TJSDoc already allows full customization. I should hit the full public launch on NPM `0.1.0` by the end of the weekend.

**Comment by heath-guidewire** [comment]
I agree… I’m going to redo my PR in a fork of your Repo… Of course maybe I should wait a few days, but I will be able to use it immediately if I do it from the fork.  I will attempt a PR after that.  I also will look at your new project and see how well it suits my company’s needs.  Hopefully I’ll switch us over if it seems stable and usable.

**Comment by typhonrt** [comment]
You should probably wait to check out TJSDoc in the coming days as I'll likely be deleting this ESDoc fork and orphaning all of my ESDoc plugins. So quite likely working on a PR for this repo is not an effective use of your time.

**Comment by heath-guidewire** [comment]
If I didn’t have a dead-line for this, I would definitely do as you suggest.  But at least for the interim I’ll have a version of your repo with my enhancement in it.  I will make sure to investigate your TJSDoc repo once it is available

**Pull request closed without merging**
